#
# Makefile to build TeamSpeak 3 SDK Server Sample on Linux
#

CFLAGS = -Wall -g -O0

all: libs ts3_server_sample

libs: ../../bin/linux/x86/libts3server.so
	ln -sf ../../bin/linux/x86/libts3server.so .

ts3_server_sample: id_io.o main.o
	gcc -o ts3_server_sample id_io.o main.o -Wl,-rpath,"." -L../../bin/linux/x86/ -lts3server

main.o: main.c
	gcc -c -I../../include main.c $(CFLAGS)

id_io.o: id_io.c
	gcc -c -I../../include id_io.c $(CFLAGS)

clean:
	rm -rf *.o ts3_server_sample
