#
# Makefile to build TeamSpeak 3 SDK Client Sample on Linux
#

CFLAGS = -Wall -g -O0

all: libs ts3_client_sample

libs: ../../bin/linux/amd64/libts3client.so
	ln -sf ../../bin/linux/amd64/libts3client.so .
	ln -sf ../../bin/linux/amd64/soundbackends .

ts3_client_sample: main.o
	gcc -o ts3_client_sample main.o -Wl,-rpath,"." -L../../bin/linux/amd64 -lts3client -ldl

main.o: main.c
	gcc -c -I../../include main.c $(CFLAGS)

clean:
	rm -rf *.o ts3_client_sample
