#
# Makefile to build TeamSpeak 3 SDK Server FileTransfer Sample on Linux
#

CFLAGS = -Wall -g -O0

all: libs ts3_server_filetransfer_sample

libs: ../../bin/linux/x86/libts3server.so
	ln -sf ../../bin/linux/x86/libts3server.so .

ts3_server_filetransfer_sample: main.o
	gcc -o ts3_server_filetransfer_sample main.o -Wl,-rpath,"." -L../../bin/linux/x86/ -lts3server

main.o: main.c
	gcc -c -I../../include main.c $(CFLAGS)

clean:
	rm -rf *.o ts3_server_filetransfer_sample
